git:
    depth: 10

language: php

matrix:
  include:
    - php: 5.6
      sudo: false
      env: SYMFONY_VERSION=2.8.* FUNCTIONAL_TESTS=false
    - php: 7.0
      sudo: false
      env: SYMFONY_VERSION=2.8.* FUNCTIONAL_TESTS=false
    - php: 5.6
      sudo: false
      env: SYMFONY_VERSION=3.0.* FUNCTIONAL_TESTS=false SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 7.0
      sudo: false
      env: SYMFONY_VERSION=3.0.* FUNCTIONAL_TESTS=false SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 7.0
      sudo: required
      services: docker
      env: SYMFONY_VERSION=2.8.* FUNCTIONAL_TESTS=true
    - php: 7.0
      sudo: required
      services: docker
      env: SYMFONY_VERSION=3.0.* FUNCTIONAL_TESTS=true

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/php-amqp
        - $HOME/rabbitmq-c
        - $HOME/bin

install:
    - rm $HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini;
    - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - pkg/amqp-ext/travis/build-php-amqp-ext;
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - composer update
    - if [ "$FUNCTIONAL_TESTS" = true ]; then docker --version; fi
    - if [ "$FUNCTIONAL_TESTS" = true ]; then docker-compose --version; fi
    - if [ "$FUNCTIONAL_TESTS" = true ]; then bin/dev -b; fi

script:
    - if [ "$FUNCTIONAL_TESTS" = false ]; then bin/phpunit --exclude-group=functional; fi
    - if [ "$FUNCTIONAL_TESTS" = true ]; then bin/dev -t; fi
