sudo: required

git:
    depth: 10

language: php

php:
    - '5.6'
    - '7.0'

services:
    - docker

cache:
    bundler: true
    directories:
        - $HOME/.composer/cache
        - $HOME/php-amqp
        - $HOME/rabbitmq-c

install:
    - sudo /etc/init.d/mysql stop
    - rm $HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - pkg/amqp-ext/travis/build-php-amqp-ext
    - cd $TRAVIS_BUILD_DIR
    - composer self-update
    - composer update --prefer-source

script:
    - bin/phpunit --exclude-group=functional
    - bin/dev -bt