git:
    depth: 10

language: php

matrix:
  include:
    - php: 7.1
      sudo: false
      env: SYMFONY_VERSION=3.4.* PHPSTAN=true
    - php: 7.1
      sudo: false
      env: SYMFONY_VERSION=3.4.* PHP_CS_FIXER=true
    - php: 7.1
      sudo: false
      env: SYMFONY_VERSION=3.4.* UNIT_TESTS=true
    - php: 7.1
      sudo: false
      env: SYMFONY_VERSION=4.0.* UNIT_TESTS=true
    - php: 7.2
      sudo: false
      env: SYMFONY_VERSION=4.0.* UNIT_TESTS=true
    - php: 7.1
      services: docker
      sudo: required
      env: SYMFONY_VERSION=3.4.* FUNCTIONAL_TESTS=true PREPARE_CONTAINER=true
    - php: 7.1
      sudo: required
      services: docker
      env: SYMFONY_VERSION=4.0.* FUNCTIONAL_TESTS=true PREPARE_CONTAINER=true
    - php: 7.1
      sudo: required
      services: docker
      env: SYMFONY_VERSION=3.4.* RDKAFKA_TESTS=true PREPARE_CONTAINER=true
  allow_failures:
    - env: SYMFONY_VERSION=3.4.* RDKAFKA_TESTS=true PREPARE_CONTAINER=true

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - echo "extension = mongodb.so" >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - rm $HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini;
    - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - php ./bin/fix-symfony-version.php "$SYMFONY_VERSION"
    - composer install
    - if [ "$PREPARE_CONTAINER" = true ]; then docker --version; fi
    - if [ "$PREPARE_CONTAINER" = true ]; then docker-compose --version; fi
    - if [ "$PREPARE_CONTAINER" = true ]; then bin/dev -b; fi

script:
    - IFS=$'\n'; COMMIT_SCA_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")); unset IFS
    - if [ "$PHP_CS_FIXER" = true ]; then ./bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --stop-on-violation --using-cache=no --path-mode=intersection -- "${COMMIT_SCA_FILES[@]}"; fi
    - if [ "$PHPSTAN" = true ]; then docker run --workdir="/mqdev" -v "`pwd`:/mqdev" --rm enqueue/dev:latest php -d memory_limit=1024M bin/phpstan analyse -l 1 -c phpstan.neon -- "${COMMIT_SCA_FILES[@]}" ; fi
    - if [ "$UNIT_TESTS" = true ]; then bin/phpunit --exclude-group=functional; fi
    - if [ "$FUNCTIONAL_TESTS" = true ]; then bin/test.sh --exclude-group=rdkafka; fi
    - if [ "RDKAFKA_TESTS" = true ]; then bin/test.sh --group=rdkafka; fi
    
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3f8b3668e7792de23a49
    on_success: change  
    on_failure: always  
    on_start: never     

