version: '2'

services:
  dev:
    image: enqueue/dev:latest
    depends_on:
      - rabbitmq
      - mysql
      - redis
      - beanstalkd
      - gearmand
      - kafka
      - zookeeper
      - google-pubsub
      - rabbitmqssl
      - mongo
      - localstack
    volumes:
      - './:/mqdev'
    environment:
      - AMQP_DSN=amqp://guest:guest@rabbitmq:5672/mqdev
      - AMQPS_DSN=amqps://guest:guest@rabbitmqssl:5671
      - DOCTRINE_DSN=mysql://root:rootpass@mysql/mqdev
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VHOST=mqdev
      - RABBITMQ_AMQP__PORT=5672
      - RABBITMQ_STOMP_PORT=61613
      - DOCTRINE_DRIVER=pdo_mysql
      - DOCTRINE_HOST=mysql
      - DOCTRINE_PORT=3306
      - DOCTRINE_DB_NAME=mqdev
      - DOCTRINE_USER=root
      - DOCTRINE_PASSWORD=rootpass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AWS_SQS_KEY=key
      - AWS_SQS_SECRET=secret
      - AWS_SQS_REGION=us-east-1
      - AWS_SQS_ENDPOINT=http://localstack:4576
      - AWS_SQS_VERSION=latest
      - BEANSTALKD_HOST=beanstalkd
      - BEANSTALKD_PORT=11300
      - BEANSTALKD_DSN=beanstalk://beanstalkd:11300
      - GEARMAN_DSN=gearman://gearmand:4730
      - RDKAFKA_HOST=kafka
      - RDKAFKA_PORT=9092
      - PUBSUB_EMULATOR_HOST=http://google-pubsub:8085
      - GCLOUD_PROJECT=mqdev
      - MONGO_DSN=mongodb://mongo

  rabbitmq:
    image: 'enqueue/rabbitmq:3.7'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=mqdev
    ports:
      - "15677:15672"

  rabbitmqssl:
    image: 'enqueue/rabbitmq-ssl:latest'
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'

  beanstalkd:
      image: 'jonbaldie/beanstalkd'

  gearmand:
      image: 'artefactual/gearmand'

  redis:
    image: 'redis:3'
    ports:
      - "6379:6379"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mqdev

  generate-changelog:
    image: enqueue/generate-changelog:latest
    # build: { context: docker, dockerfile: Dockerfile.generate-changelog }
    volumes:
      - ./:/mqdev

  zookeeper:
    image: 'wurstmeister/zookeeper'
    ports:
      - '2181:2181'

  kafka:
    image: 'wurstmeister/kafka:0.10.2.1'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  google-pubsub:
      image: 'google/cloud-sdk:latest'
      entrypoint: 'gcloud beta emulators pubsub start --host-port=0.0.0.0:8085'

  mongo:
      image: mongo:3.7
      ports:
        - "27017:27017"

  localstack:
    image: 'localstack/localstack:latest'
    ports:
      - '4576:4576'
    environment:
      HOSTNAME_EXTERNAL: 'localstack'
      SERVICES: 'sqs'

