version: '2'

services:
  dev:
    image: enqueue/dev:latest
    # build: { context: docker, dockerfile: Dockerfile }
    depends_on:
      - rabbitmq
      - mysql
      - redis
      - beanstalkd
      - gearmand
      - kafka
      - zookeeper
      - google-pubsub
      - rabbitmqssl
    volumes:
      - './:/mqdev'
    environment:
      - AMQP_DSN=amqp://guest:guest@rabbitmq:5672/mqdev
      - AMQPS_DSN=amqps://guest:guest@rabbitmqssl:5671
      - DOCTINE_DSN=mysql://root:rootpass@mysql/mqdev
      - SYMFONY__RABBITMQ__HOST=rabbitmq
      - SYMFONY__RABBITMQ__USER=guest
      - SYMFONY__RABBITMQ__PASSWORD=guest
      - SYMFONY__RABBITMQ__VHOST=mqdev
      - SYMFONY__RABBITMQ__AMQP__PORT=5672
      - SYMFONY__RABBITMQ__STOMP__PORT=61613
      - SYMFONY__DB__DRIVER=pdo_mysql
      - SYMFONY__DB__HOST=mysql
      - SYMFONY__DB__PORT=3306
      - SYMFONY__DB__NAME=mqdev
      - SYMFONY__DB__USER=root
      - SYMFONY__DB__PASSWORD=rootpass
      - SYMFONY__REDIS__HOST=redis
      - SYMFONY__REDIS__PORT=6379
      - AWS__SQS__KEY=$ENQUEUE_AWS__SQS__KEY
      - AWS__SQS__SECRET=$ENQUEUE_AWS__SQS__SECRET
      - AWS__SQS__REGION=$ENQUEUE_AWS__SQS__REGION
      - BEANSTALKD_HOST=beanstalkd
      - BEANSTALKD_PORT=11300
      - BEANSTALKD_DSN=beanstalk://beanstalkd:11300
      - GEARMAN_DSN=gearman://gearmand:4730
      - RDKAFKA_HOST=kafka
      - RDKAFKA_PORT=9092
      - PUBSUB_EMULATOR_HOST=http://google-pubsub:8085
      - GCLOUD_PROJECT=mqdev

  rabbitmq:
    image: 'enqueue/rabbitmq:latest'
    # build: { context: docker, dockerfile: Dockerfile.rabbitmq }
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=mqdev
    ports:
      - "15677:15672"

  rabbitmqssl:
    image: 'enqueue/rabbitmq-ssl:latest'
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'

  beanstalkd:
      image: 'jonbaldie/beanstalkd'

  gearmand:
      image: 'artefactual/gearmand'

  redis:
    image: 'redis:3'
    ports:
      - "6379:6379"

  mysql:
    image: mariadb:10
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass

  generate-changelog:
    image: enqueue/generate-changelog:latest
    # build: { context: docker, dockerfile: Dockerfile.generate-changelog }
    volumes:
      - ./:/mqdev

  zookeeper:
    image: 'wurstmeister/zookeeper'
    ports:
      - '2181:2181'

  kafka:
    image: 'wurstmeister/kafka:0.10.2.1'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  google-pubsub:
      image: 'google/cloud-sdk:latest'
      entrypoint: 'gcloud beta emulators pubsub start --host-port=0.0.0.0:8085'

volumes:
  mysql-data:
    driver: local
