services:
    enqueue.consumption.reply_extension:
        class: 'Enqueue\Consumption\Extension\ReplyExtension'
        tags:
            - { name: 'enqueue.consumption_extension', client: 'all' }
            - { name: 'enqueue.transport.consumption_extension', transport: 'all' }