services:
    enqueue.async_command.run_command_processor:
        class: 'Enqueue\AsyncCommand\RunCommandProcessor'
        public: public
        arguments:
            - '%kernel.root_dir%/..'
        tags:
            - { name: 'enqueue.client.processor' }
