sudo: false

git:
    depth: 1

language: php

php:
    - '5.6'
    - '7.0'

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer self-update
    - composer install --prefer-source --ignore-platform-reqs # ext-amqp is not installed

script:
    - vendor/bin/phpunit --exclude-group=functional
