sudo: false

git:
    depth: 1

language: php

php:
    - '5.6'
    - '7.0'

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/php-amqp
        - $HOME/rabbitmq-c

install:
    - travis/build-php-amqp-ext
    - cd $TRAVIS_BUILD_DIR
    - composer self-update
    - composer install --prefer-source

script:
    - vendor/bin/phpunit --exclude-group=functional
