sudo: false

git:
    depth: 10

language: php

php:
    - '5.6'
    - '7.0'

cache:
    directories:
        - $HOME/.composer/cache

install:
    - php Tests/fix_composer_json.php
    - composer self-update
    - composer install --ignore-platform-reqs # AMQP 1.9.3 ext is not in the distro repos.

script:
    - vendor/bin/phpunit --exclude-group=functional
