sudo: false

git:
    depth: 10

language: php

php:
    - '7.1'
    - '7.2'

cache:
    directories:
        - $HOME/.composer/cache

install:
    - php Tests/fix_composer_json.php
    - composer self-update
    - composer install

script:
    - vendor/bin/phpunit --exclude-group=functional
