services:
    enqueue.client.default.context: 
        class: 'Interop\Queue\Context'
        factory: ['@enqueue.client.default.driver', 'getContext']

    enqueue.client.default.driver_factory:
        class: 'Enqueue\Client\DriverFactory'
        arguments:
            - '@enqueue.client.default.config'
            - '@enqueue.client.default.route_collection'

    enqueue.client.default.config:
        class: 'Enqueue\Client\Config'

    enqueue.client.default.route_collection:
        class: 'Enqueue\Client\RouteCollection'
        factory: ['Enqueue\Client\RouteCollection', 'fromArray']
        arguments:
            - []

    enqueue.client.default.producer:
        class: 'Enqueue\Client\Producer'
        public: true
        arguments:
            - '@enqueue.client.default.driver'
            - '@enqueue.client.default.rpc_factory'
            - '@enqueue.client.default.client_extensions'

    enqueue.client.default.spool_producer:
        class: 'Enqueue\Client\SpoolProducer'
        public: true
        arguments:
            - '@enqueue.client.default.producer'

    enqueue.client.default.client_extensions:
        class: 'Enqueue\Client\ChainExtension'
        arguments:
            - []

    enqueue.client.default.rpc_factory:
        class: 'Enqueue\Rpc\RpcFactory'
        arguments:
            - '@enqueue.client.default.context'

    enqueue.client.default.router_processor:
        class: 'Enqueue\Client\RouterProcessor'
        arguments:
            - '@enqueue.client.default.driver'

    enqueue.client.default.processor_registry:
        class: 'Enqueue\Symfony\Client\ContainerProcessorRegistry'

    enqueue.client.default.delegate_processor:
        class: 'Enqueue\Client\DelegateProcessor'
        arguments:
            - '@enqueue.client.default.processor_registry'

    enqueue.client.default.set_router_properties_extension:
        class: 'Enqueue\Client\ConsumptionExtension\SetRouterPropertiesExtension'
        arguments:
            - '@enqueue.client.default.driver'
        tags:
            - { name: 'enqueue.consumption_extension', priority: 100, client: 'default' }

    enqueue.client.default.queue_consumer:
        class: 'Enqueue\Consumption\QueueConsumer'
        arguments:
            - '@enqueue.client.default.context'
            - '@enqueue.client.default.consumption_extensions'
            - ~
            - ~

    enqueue.client.default.consumption_extensions:
        class: 'Enqueue\Consumption\ChainExtension'
        arguments:
            - []

    enqueue.client.default.consume_messages_command:
        class: 'Enqueue\Symfony\Client\ConsumeMessagesCommand'
        arguments:
            - '@enqueue.client.default.queue_consumer'
            - '@enqueue.client.default.delegate_processor'
            - '@enqueue.client.default.driver'
        tags:
            - { name: 'console.command' }

    enqueue.client.default.produce_message_command:
        class: 'Enqueue\Symfony\Client\ProduceMessageCommand'
        arguments:
            - '@enqueue.client.default.producer'
        tags:
            - { name: 'console.command' }

    enqueue.client.default.setup_broker_command:
        class: 'Enqueue\Symfony\Client\SetupBrokerCommand'
        arguments:
            - '@enqueue.client.default.driver'
        tags:
            - { name: 'console.command' }

    enqueue.client.default.routes_command:
        class: 'Enqueue\Symfony\Client\RoutesCommand'
        arguments:
            - '@enqueue.client.default.config'
            - '@enqueue.client.default.route_collection'
        tags:
            - { name: 'console.command' }

    # todo
    enqueue.profiler.message_queue_collector:
        class: 'Enqueue\Bundle\Profiler\MessageQueueCollector'
        arguments:
            - '@enqueue.client.default.producer'
        tags:
            - { name: 'data_collector', template: '@Enqueue/Profiler/panel.html.twig', id: 'enqueue.message_queue' }

    enqueue.client.default.flush_spool_producer_listener:
        class: 'Enqueue\Symfony\Client\FlushSpoolProducerListener'
        arguments:
            - '@enqueue.client.default.spool_producer'
        tags:
            - { name: 'kernel.event_subscriber' }
            
    Enqueue\Client\ProducerInterface:
        public: true
        alias: 'enqueue.client.default.producer'
        
    Enqueue\Client\SpoolProducer:
        public: true
        alias: 'enqueue.client.default.spool_producer'
