services:
    # todo
    enqueue.profiler.message_queue_collector:
        class: 'Enqueue\Bundle\Profiler\MessageQueueCollector'
        arguments:
            - '@enqueue.client.default.producer'
        tags:
            - { name: 'data_collector', template: '@Enqueue/Profiler/panel.html.twig', id: 'enqueue.message_queue' }

    # todo
    enqueue.client.default.flush_spool_producer_listener:
        class: 'Enqueue\Symfony\Client\FlushSpoolProducerListener'
        arguments:
            - '@enqueue.client.default.spool_producer'
        tags:
            - { name: 'kernel.event_subscriber' }
