services:
    enqueue.events.registry:
        class: 'Enqueue\Bundle\Events\ContainerAwareRegistry'
        public: false
        arguments: [[]]
        calls:
            -  ['setContainer', ['@service_container']]

    enqueue.events.async_listener:
        class: 'Enqueue\Bundle\Events\AsyncListener'
        public: false
        arguments: ['@enqueue.client.producer', '@enqueue.events.registry']


    enqueue.events.event_dispatcher:
        class: 'Enqueue\Bundle\Events\ProxyEventDispatcher'
        public: false
        arguments:
            - '@event_dispatcher'
            - '@enqueue.events.async_listener'

    enqueue.events.async_processor:
        class: 'Enqueue\Bundle\Events\AsyncProcessor'
        arguments:
            - '@enqueue.events.registry'
            - '@enqueue.events.event_dispatcher'
        tags:
            - {name: 'enqueue.client.processor' }
