parameters:
    enqueue.job.unique_job_table_name: 'enqueue_job_unique'

services:
    enqueue.job.storage:
        class: 'Enqueue\JobQueue\Doctrine\JobStorage'
        arguments:
            - '@doctrine'
            - 'Enqueue\JobQueue\Doctrine\Entity\Job'
            - '%enqueue.job.unique_job_table_name%'

    enqueue.job.processor:
        class: 'Enqueue\JobQueue\JobProcessor'
        arguments:
            - '@enqueue.job.storage'
            - '@enqueue.client.producer'

    enqueue.job.runner:
        class: 'Enqueue\JobQueue\JobRunner'
        arguments:
            - '@enqueue.job.processor'

    enqueue.job.calculate_root_job_status_service:
        class: 'Enqueue\JobQueue\CalculateRootJobStatusService'
        arguments:
            - '@enqueue.job.storage'

    enqueue.job.calculate_root_job_status_processor:
        class: 'Enqueue\JobQueue\CalculateRootJobStatusProcessor'
        arguments:
            - '@enqueue.job.storage'
            - '@enqueue.job.calculate_root_job_status_service'
            - '@enqueue.client.producer'
            - '@logger'
        tags:
            - { name: 'enqueue.client.processor' }

    enqueue.job.dependent_job_processor:
        class: 'Enqueue\JobQueue\DependentJobProcessor'
        arguments:
            - '@enqueue.job.storage'
            - '@enqueue.client.producer'
            - '@logger'
        tags:
            - { name: 'enqueue.client.processor' }

    enqueue.job.dependent_job_service:
        class: 'Enqueue\JobQueue\DependentJobService'
        arguments:
            - '@enqueue.job.storage'
