services:
    enqueue.locator:
        class: 'Symfony\Component\DependencyInjection\ServiceLocator'
        arguments:
            - []
        tags: ['container.service_locator']

    enqueue.consume_command:
        class: 'Enqueue\Symfony\Consumption\ConfigurableConsumeCommand'
        public: true
        arguments:
            - '@enqueue.locator'
            - 'enqueue.transport.%s.queue_consumer'
            - 'enqueue.transport.%s.processor_registry'
        tags:
            - { name: 'console.command' }
