sudo: false

git:
    depth: 10

language: php


php:
    - '7.1'

services:
  - mongodb

before_install:
    - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

cache:
    directories:
        - $HOME/.composer/cache

install:
    - php Tests/fix_composer_json.php
    - composer self-update
    - composer install --prefer-source

script:
    - vendor/bin/phpunit --exclude-group=functional
