title: enqueue-dev
description: A Jekyll theme for documentation
baseurl: "/enqueue-dev/" # the subpath of your site, e.g. /blog
url: "https://steveb-p.github.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "enqueue-dev on GitHub":
    - "//github.com/enqueue-dev/enqueue-dev"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: dark

remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-seo-tag
