sudo: false

git:
    depth: 1

language: php

php:
    - '5.6'
    - '7.0'

cache:
    directories:
        - $HOME/.composer/cache

install:
    - pecl install gearman
    - composer self-update
    - composer install --prefer-source

script:
    - vendor/bin/phpunit --exclude-group=functional
