sudo: false

git:
    depth: 10

addons:
  apt_packages:
    - libgearman-dev

language: php

php:
    - '5.6'
    - '7.0'

cache:
    directories:
        - $HOME/.composer/cache

install:
    - pecl install gearman
    - composer self-update
    - composer install --prefer-source

script:
    - vendor/bin/phpunit --exclude-group=functional
